const AqiModel = require('../models/AqiModel')
const ThresholdModel = require('../models/ThresholdModel')
const Device = require('../models/DeviceModel')
const getVisibleDeviceIds = require('../utils/visibleDevices')

// GET /api/alerts/current — alerts for *latest* reading of each user device.
const getCurrentAlerts = async (req, res) => {
  try {
    const userDeviceIds = await getVisibleDeviceIds(req.user)
    if (userDeviceIds.length === 0) return res.status(200).json([])

    const thresholdDoc = await ThresholdModel.findOne().sort({ createdAt: -1 }).lean()
    const limits = buildLimits(thresholdDoc)

    const latestReadings = await AqiModel.aggregate([
      { $match: { deviceId: { $in: userDeviceIds } } },
      { $sort: { createdAt: -1 } },
      { $group: { _id: '$deviceId', latest: { $first: '$$ROOT' } } }
    ])

    const devices = await Device.find({ deviceId: { $in: userDeviceIds } }).lean()
    const deviceMap = Object.fromEntries(devices.map(d => [d.deviceId, d]))

    const alerts = []
    for (const r of latestReadings) {
      const reading = r.latest
      const device = deviceMap[reading.deviceId]
      if (!device) continue

      for (const f of FIELDS) {
        if (reading[f] != null && reading[f] > limits[f]) {
          alerts.push({
            deviceId: reading.deviceId,
            name: device.name,
            room: device.room,
            field: f,
            value: reading[f],
            limit: limits[f],
            severity: reading[f] > limits[f] * 1.5 ? 'high' : 'warning',
            at: reading.createdAt,
          })
        }
      }
    }
    res.status(200).json(alerts)
  } catch (error) {
    res.status(500).json({ error: error.message })
  }
}

// GET /api/alerts/history?days=7 — all alert events in the past N days.
// Generated by scanning historical readings — we don't persist alerts separately.
const getAlertHistory = async (req, res) => {
  try {
    const userDeviceIds = await getVisibleDeviceIds(req.user)
    if (userDeviceIds.length === 0) return res.status(200).json([])

    const days = Math.min(parseInt(req.query.days || '1', 10), 3)
    const since = new Date(Date.now() - days * 86400 * 1000)

    const thresholdDoc = await ThresholdModel.findOne().sort({ createdAt: -1 }).lean()
    const limits = buildLimits(thresholdDoc)

    // Hard limit of 2000 readings to prevent OOM on constrained hosting.
    // At ~1 reading/2s per device this covers ~1 hour per device, enough
    // to detect threshold-crossing transitions without loading the full dataset.
    const readings = await AqiModel.find({
      deviceId: { $in: userDeviceIds },
      createdAt: { $gte: since }
    }).sort({ createdAt: -1 }).limit(2000).lean()

    const devices = await Device.find({ deviceId: { $in: userDeviceIds } }).lean()
    const deviceMap = Object.fromEntries(devices.map(d => [d.deviceId, d]))

    // Deduplicate: only emit an alert for each (device, field) when it transitions
    // *into* exceeding the threshold, not for every consecutive reading.
    // Group by (deviceId, field) ascending in time, mark transitions.
    const byDeviceField = {}
    for (const r of [...readings].reverse()) {
      for (const f of FIELDS) {
        const key = `${r.deviceId}|${f}`
        const exceeded = r[f] != null && r[f] > limits[f]
        const prev = byDeviceField[key]
        if (exceeded && (!prev || !prev.lastExceeded)) {
          // transition into exceeding — record an alert event
          if (!prev) byDeviceField[key] = { events: [] }
          byDeviceField[key].events.push({
            deviceId: r.deviceId,
            field: f,
            value: r[f],
            limit: limits[f],
            severity: r[f] > limits[f] * 1.5 ? 'high' : 'warning',
            at: r.createdAt,
          })
        }
        byDeviceField[key] = byDeviceField[key] || { events: [] }
        byDeviceField[key].lastExceeded = exceeded
      }
    }

    const allEvents = []
    for (const k of Object.keys(byDeviceField)) {
      for (const e of byDeviceField[k].events) {
        const device = deviceMap[e.deviceId]
        if (!device) continue
        allEvents.push({
          ...e,
          name: device.name,
          room: device.room,
        })
      }
    }
    allEvents.sort((a, b) => new Date(b.at) - new Date(a.at))

    res.status(200).json(allEvents.slice(0, 100))
  } catch (error) {
    res.status(500).json({ error: error.message })
  }
}

const FIELDS = ['Aqi', 'PM25', 'PM10', 'CO2', 'TVOC', 'Formaldehyde']

function buildLimits(thresholdDoc) {
  return {
    Aqi:          thresholdDoc?.Aqi          ?? 100,
    PM25:         thresholdDoc?.PM25         ?? 40,
    PM10:         thresholdDoc?.PM10         ?? 100,
    CO2:          thresholdDoc?.CO2          ?? 1000,
    TVOC:         thresholdDoc?.TVOC         ?? 500,
    Formaldehyde: thresholdDoc?.Formaldehyde ?? 100,
  }
}

module.exports = { getCurrentAlerts, getAlertHistory }
